print "██████╗ ██████╗  ██████╗      ██╗███████╗ ██████╗████████╗    ██╗  ██╗    ██████╗ "
print "██╔══██╗██╔══██╗██╔═══██╗     ██║██╔════╝██╔════╝╚══██╔══╝    ╚██╗██╔╝    ╚════██╗"
print "██████╔╝██████╔╝██║   ██║     ██║█████╗  ██║        ██║        ╚███╔╝      █████╔╝"
print "██╔═══╝ ██╔══██╗██║   ██║██   ██║██╔══╝  ██║        ██║        ██╔██╗     ██╔═══╝ "
print "██║     ██║  ██║╚██████╔╝╚█████╔╝███████╗╚██████╗   ██║       ██╔╝ ██╗    ███████╗"
print "╚═╝     ╚═╝  ╚═╝ ╚═════╝  ╚════╝ ╚══════╝ ╚═════╝   ╚═╝       ╚═╝  ╚═╝    ╚══════╝"                                                                             
print "Project X 2 successfully set up!"
print "Developer: WeepingAngel"
print "Check out our Discord: .gg/q3KRw62gTx"
print "System checks:"
print "Injection Method: successful"
print "BTInjector: successful"
print "Loadstring: successful"
